/*
  MPM FUNDRAISER — DATA FILE
  Generated by admin.html — replace the copy next to index.html on your host.
*/
const FUNDRAISING_DATA = {
  "projectName": "Server",
  "goal": 0,
  "currency": "LKR",
  "startDate": "2026-09-01",
  "donations": [
    {
      "name": "Dulminda",
      "amount": 2000,
      "date": "2026-08-12",
      "note": "",
      "anonymous": false
    },
    {
      "name": "Ads",
      "amount": 1300,
      "date": "2026-09-01",
      "note": "",
      "anonymous": false
    }
  ],
  "expenses": [
    {
      "title": "Domain Renewal",
      "amount": 3821.77,
      "date": "2026-09-01",
      "category": "Domain"
    }
  ]
};
