/*
  MPM FUNDRAISER — DATA FILE
  Generated by admin.html — replace the copy next to index.html on your host.
*/
const FUNDRAISING_DATA = {
  "projectName": "MPM Server & Domain",
  "goal": 5000,
  "currency": "LKR",
  "startDate": "2026-08-01",
  "donations": [
    {
      "name": "Dasun",
      "amount": 1000,
      "date": "2026-08-01",
      "note": "Keep going",
      "anonymous": false
    }
  ],
  "expenses": []
};
